pipeline{
     agent any
     tools{
     maven 'M2_HOME'
     }
     
     stages{
       stage('maven1'){
           steps{
           sh 'mvn clean validate compile install test package'
           }
       }
       stage('upload artifact'){
            steps{
            sh 'curl -uadmin:AP3yQAuEtNW52NMLC1yXozr4nbt -T \
            target/bio*.jar "http://ec2-54-157-132-219.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
            }
       }
     
     }
}